<?php
namespace App\Model;


use Laventure\Foundation\Database\ORM\Model;


/**
 * Class Product
 * @package App\Model
 *
 * <Generated By Laventure>
*/
class Product extends  Model
{

       /**
        * @var string
       */
       protected $table = 'products';




       /**
        * attributes where can fill data
        * @var array
       */
       protected $fillable = [
           'title',
           'price',
           'description',
           'featured'
       ];




       /**
        * @var array
       */
       protected $hidden = [];





       /**
        * @var array
       */
       protected $guarded = ['id'];
}
