<?php
namespace App\Http\Controller\Admin;


use App\Http\Controller\Common\AdminController;
use Laventure\Component\Http\Request\Request;
use Laventure\Component\Http\Response\Response;


/**
 * Class DashboardController
 * @package App\Http\Controller\Admin
 *
 * <Generated By Laventure 27/02/2022 02:57:56>
*/
class DashboardController extends AdminController
{

        /**
         * @param Request $request
         * @return Response
        */
        public function index(Request $request): Response
        {
             return $this->render('admin/dashboard/index.php');
        }
}
