<?php
namespace App\Http\Controller\Admin;


use App\Http\Controller\Common\AdminController;
use App\Repository\UserRepository;
use Laventure\Component\Http\Request\Request;
use Laventure\Component\Http\Response\Response;


/**
 * Class UserController
 * @package App\Http\Controller\Admin
 *
 * <Generated By Laventure 27/02/2022 03:19:17>
*/
class UserController extends AdminController
{


    /**
     * @var UserRepository
    */
    protected $userRepository;


    /**
     * @param UserRepository $userRepository
    */
    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }



    /**
     * @param Request $request
     * @return Response
    */
    public function index(Request $request): Response
    {
        $users = $this->userRepository->findAll();

        return $this->render('admin/user/index.php', compact('users'));
    }
}
